import Link from "next/link";
import { Car, ArrowLeft, Mail, FileText } from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — claimo.",
  description: "Terms and conditions for using claimo.",
};

const sections = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: `By accessing or using claimo. ("the Service", "claimo"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.

claimo is operated as an independent personal finance tool. These terms constitute the entire agreement between you and claimo regarding the use of the Service.`,
  },
  {
    id: "description",
    title: "Description of Service",
    content: `claimo is a ride expense automation tool that:

• Connects to your Gmail account (with your explicit consent) to read ride receipt emails from Uber and Rapido
• Extracts trip data (date, amount, locations) from those receipts
• Displays your expense history and generates PDF reimbursement reports

The Service is provided on an "as is" basis and is intended for personal expense tracking and employer reimbursement purposes.`,
  },
  {
    id: "account",
    title: "Account & Access",
    items: [
      {
        label: "Google Sign-In",
        desc: "You must sign in with a valid Google account to use claimo. By doing so, you authorise claimo to access your Gmail account for the sole purpose of reading ride receipt emails.",
      },
      {
        label: "Account Responsibility",
        desc: "You are responsible for maintaining the security of your account. Notify us immediately at gajanansr.work@gmail.com if you suspect unauthorised access.",
      },
      {
        label: "One account per person",
        desc: "Accounts are for individual use only. You may not share, sell, or transfer your account to another person.",
      },
    ],
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    content: `You agree to use claimo only for lawful purposes. You must not:`,
    items: [
      { label: "Misuse the Service", desc: "Attempt to reverse engineer, decompile, or extract the source code of the Service." },
      { label: "Overload infrastructure", desc: "Use automated scripts or bots to make excessive API requests." },
      { label: "Circumvent security", desc: "Attempt to bypass Row Level Security, authentication, or any access controls." },
      { label: "Fraudulent claims", desc: "Use the Service to generate false or misleading reimbursement reports." },
    ],
  },
  {
    id: "data-gmail",
    title: "Gmail Data & Google API Policy",
    content: `claimo's use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements.

Specifically:
• We only request Gmail access scopes required to query ride receipt emails
• We do not use Gmail data for advertising or to train AI/ML models
• We do not share Gmail data with third parties except as necessary to operate the Service (e.g., storing receipts in your private Supabase database)
• You can revoke Gmail access at any time via myaccount.google.com/permissions`,
  },
  {
    id: "ip",
    title: "Intellectual Property",
    content: `The claimo brand, logo, UI design, and source code are proprietary and owned by the claimo developer. You may not reproduce or redistribute any part of the Service without prior written permission.

Your data (receipts, reports) remains entirely yours. You own it and can export or delete it at any time.`,
  },
  {
    id: "disclaimers",
    title: "Disclaimers & Limitations",
    items: [
      {
        label: "No warranty",
        desc: "The Service is provided without warranty of any kind. We do not guarantee that receipt parsing will always be accurate, or that the Service will be uninterrupted or error-free.",
      },
      {
        label: "Reimbursement accuracy",
        desc: "PDF reports generated by claimo are based on data extracted from emails. You are responsible for verifying the accuracy of all amounts before submitting to an employer.",
      },
      {
        label: "Limitation of liability",
        desc: "To the fullest extent permitted by law, claimo shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.",
      },
    ],
  },
  {
    id: "termination",
    title: "Termination",
    content: `You may stop using the Service and delete your account at any time from Settings → Delete Account.

We reserve the right to suspend or terminate accounts that violate these Terms, with or without notice, at our sole discretion.`,
  },
  {
    id: "changes",
    title: "Changes to Terms",
    content: `We may revise these Terms of Service at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes are posted constitutes your acceptance of the revised terms.`,
  },
  {
    id: "governing-law",
    title: "Governing Law",
    content: `These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in India.`,
  },
  {
    id: "contact",
    title: "Contact",
    content: `For any questions about these Terms of Service, please reach out:`,
    contact: true,
  },
];

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-zinc-200 font-sans antialiased">

      {/* Nav */}
      <nav className="border-b border-zinc-900 h-14 flex items-center justify-between px-6 lg:px-12 shrink-0 sticky top-0 bg-black/90 backdrop-blur-sm z-10">
        <Link href="/" className="flex items-center gap-2">
          <Car className="h-4 w-4 text-zinc-300" />
          <span className="text-zinc-100 font-bold text-[15px] tracking-tight">
            claimo<span className="text-emerald-500">.</span>
          </span>
        </Link>
        <Link
          href="/"
          className="flex items-center gap-1.5 text-[12px] text-zinc-500 hover:text-zinc-200 transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to home
        </Link>
      </nav>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-12 lg:py-16">

        {/* Header */}
        <div className="mb-10">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="h-5 w-5 text-zinc-400" />
            <Badge variant="outline" className="text-zinc-400 border-zinc-800 bg-zinc-900/40 text-[11px]">
              Legal
            </Badge>
          </div>
          <h1 className="text-3xl font-bold text-zinc-100 tracking-tight mb-3">Terms of Service</h1>
          <p className="text-zinc-500 text-sm">Last updated: June 17, 2025</p>
        </div>

        <Separator className="bg-zinc-900 mb-10" />

        {/* Table of contents */}
        <div className="bg-zinc-950 border border-zinc-900 rounded-xl p-5 mb-10">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-zinc-500 mb-3">Contents</p>
          <ol className="space-y-1.5">
            {sections.map((s, i) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-[13px] text-zinc-400 hover:text-zinc-200 transition-colors flex items-center gap-2"
                >
                  <span className="text-zinc-700 text-[11px] tabular-nums">{String(i + 1).padStart(2, "0")}</span>
                  {s.title}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* Sections */}
        <div className="space-y-12">
          {sections.map((section, i) => (
            <section key={section.id} id={section.id} className="scroll-mt-20">
              <div className="flex items-center gap-3 mb-4">
                <span className="text-[11px] font-bold text-zinc-700 tabular-nums">{String(i + 1).padStart(2, "0")}</span>
                <h2 className="text-lg font-bold text-zinc-100">{section.title}</h2>
              </div>

              {section.content && !section.contact && (
                <p className="text-zinc-400 text-[14px] leading-relaxed whitespace-pre-line">
                  {section.content}
                </p>
              )}

              {section.contact && (
                <div className="space-y-4">
                  <p className="text-zinc-400 text-[14px] leading-relaxed">{section.content}</p>
                  <a
                    href="mailto:gajanansr.work@gmail.com"
                    className="inline-flex items-center gap-2.5 bg-zinc-950 border border-zinc-800 hover:border-zinc-700 hover:bg-zinc-900/40 rounded-xl px-4 py-3 transition-all group"
                  >
                    <Mail className="h-4 w-4 text-zinc-400 shrink-0" />
                    <div>
                      <p className="text-[13px] font-semibold text-zinc-200 group-hover:text-zinc-100 transition-colors">
                        gajanansr.work@gmail.com
                      </p>
                      <p className="text-[11px] text-zinc-600">Terms & legal inquiries</p>
                    </div>
                  </a>
                </div>
              )}

              {section.items && (
                <div className="space-y-3 mt-3">
                  {section.items.map((item) => (
                    <div key={item.label} className="bg-zinc-950 border border-zinc-900 rounded-lg p-4">
                      <p className="text-[13px] font-semibold text-zinc-200 mb-1">{item.label}</p>
                      <p className="text-[13px] text-zinc-500 leading-relaxed">{item.desc}</p>
                    </div>
                  ))}
                </div>
              )}

              {i < sections.length - 1 && <Separator className="bg-zinc-900 mt-12" />}
            </section>
          ))}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-zinc-900 h-12 flex items-center justify-between px-6 lg:px-12 shrink-0 mt-8">
        <span className="text-[12px] text-zinc-700 font-medium">
          claimo<span className="text-emerald-600">.</span>
        </span>
        <div className="flex items-center gap-4">
          <Link href="/privacy" className="text-[11px] text-zinc-700 hover:text-zinc-400 transition-colors">Privacy</Link>
          <Link href="/terms" className="text-[11px] text-zinc-500 hover:text-zinc-400 transition-colors">Terms</Link>
        </div>
      </footer>
    </div>
  );
}
